import React,{useEffect,useState}from"react";
import{Bot,CheckCircle2,Copy,Database,ExternalLink,KeyRound,RefreshCw,Search,Send,Server,ShieldCheck,Trash2,Wifi,XCircle}from"lucide-react";

const when=value=>value?new Date(value).toLocaleString():"—";
async function api(url,options){const response=await fetch(url,{cache:"no-store",...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data}
function Notice({value}){return value?<div className={"adminNotice "+(value.ok?"ok":"error")}>{value.text}</div>:null}
function Loading(){return <div className="adminModuleEmpty"><RefreshCw className="spin"/><b>Loading…</b></div>}
function Empty({children="No stored data yet."}){return <div className="adminModuleEmpty"><Database/><b>{children}</b></div>}
function Badge({children,tone=""}){return <span className={`adminBadge ${tone}`}>{children||"—"}</span>}
function Table({columns,rows,empty="No stored data yet."}){return <div className="adminTableWrap"><table className="adminTable"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,index)=><tr key={row.id||row.paymentId||row.codeId||row.reference||index}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):row[c.key]??"—"}</td>)}</tr>):<tr><td colSpan={columns.length}><Empty>{empty}</Empty></td></tr>}</tbody></table></div>}

export function SubscriptionsModule(){
 const[rows,setRows]=useState([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[notice,setNotice]=useState(null);
 const load=async(q=query)=>{setLoading(true);setNotice(null);try{const data=await api("/api/admin/subscriptions?q="+encodeURIComponent(q));setRows(data.servers||[])}catch(error){setNotice({text:error.message})}finally{setLoading(false)}};
 useEffect(()=>{load("")},[]);
 const change=async(row,action)=>{let days;if(action!=="revoke"){const raw=window.prompt(`${action==="grant"?"Grant":"Extend"} VIP for how many days?`,"30");if(raw===null)return;days=Number(raw);if(!Number.isFinite(days)||days<1)return setNotice({text:"Enter a valid number of days."})}else if(!window.confirm(`Revoke VIP from ${row.guildName||row.guildId}?`))return;setBusy(row.guildId+action);setNotice(null);try{await api(`/api/admin/subscriptions/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({guildId:row.guildId,days})});setNotice({ok:true,text:`VIP ${action} completed.`});await load()}catch(error){setNotice({text:error.message})}finally{setBusy("")}};
 return <section className="adminModule"><div className="adminModuleToolbar"><div className="adminSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search server name or Discord ID"/></div><button onClick={()=>load()}><RefreshCw/>Refresh</button></div><Notice value={notice}/>{loading?<Loading/>:<Table columns={[
  {key:"server",label:"SERVER",render:r=><div className="adminIdentity"><span>{r.icon?<img src={`https://cdn.discordapp.com/icons/${r.guildId}/${r.icon}.png?size=64`} alt=""/>:(r.guildName||"?").slice(0,1)}</span><div><b>{r.guildName||"Unknown server"}</b><small>{r.guildId}</small></div></div>},
  {key:"owner",label:"OWNER",render:r=><><b>{r.ownerName||"—"}</b><small className="adminCellSub">{r.ownerId||""}</small></>},
  {key:"plan",label:"PLAN",render:r=><Badge tone={r.status?.toLowerCase()}>{r.plan}</Badge>},
  {key:"expiresAt",label:"EXPIRES",render:r=><><span>{when(r.expiresAt)}</span><small className="adminCellSub">{r.remaining||r.status}</small></>},
  {key:"actions",label:"ACTIONS",render:r=><div className="adminRowActions">{r.status!=="ACTIVE"&&<button disabled={!!busy} onClick={()=>change(r,"grant")}>Grant VIP</button>}<button disabled={!!busy} onClick={()=>change(r,"extend")}>Extend</button>{r.status==="ACTIVE"&&<button className="danger" disabled={!!busy} onClick={()=>change(r,"revoke")}>Revoke</button>}</div>}
 ]} rows={rows} empty="No servers match this search."/>}</section>
}

export function CodesModule(){
 const[codes,setCodes]=useState([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(null),[form,setForm]=useState({codeMode:"generate",customCode:"",durationPreset:"30",durationDays:"30",maxRedemptions:"1",status:"active",expiresAt:""}),[history,setHistory]=useState(null);
 const load=async()=>{setLoading(true);try{const data=await api("/api/admin/vip-codes");setCodes(data.codes||[])}catch(error){setNotice({text:error.message})}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const create=async e=>{e.preventDefault();setNotice(null);try{const data=await api("/api/admin/vip-codes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setNotice({ok:true,text:`Code ${data.code.code} created.`});setForm(v=>({...v,customCode:""}));await load()}catch(error){setNotice({text:error.message})}};
 const patch=async(code,status)=>{try{await api(`/api/admin/vip-codes/${encodeURIComponent(code.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});await load()}catch(error){setNotice({text:error.message})}};
 const remove=async code=>{if(!window.confirm(`Delete ${code.code}?`))return;try{await api(`/api/admin/vip-codes/${encodeURIComponent(code.id)}`,{method:"DELETE"});await load()}catch(error){setNotice({text:error.message})}};
 const showHistory=async code=>{try{setHistory(await api(`/api/admin/vip-codes/${encodeURIComponent(code.id)}/history`))}catch(error){setNotice({text:error.message})}};
 return <section className="adminModule"><form className="adminCreateCard" onSubmit={create}><div><small>NEW VIP CODE</small><h3>Create activation code</h3></div><label><span>MODE</span><select value={form.codeMode} onChange={e=>setForm({...form,codeMode:e.target.value})}><option value="generate">Generate automatically</option><option value="custom">Custom code</option></select></label>{form.codeMode==="custom"&&<label><span>CUSTOM CODE</span><input value={form.customCode} onChange={e=>setForm({...form,customCode:e.target.value})} placeholder="BALTICM2026"/></label>}<label><span>DURATION</span><select value={form.durationPreset} onChange={e=>setForm({...form,durationPreset:e.target.value,durationDays:e.target.value==="custom"?form.durationDays:e.target.value})}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">365 days</option><option value="custom">Custom</option></select></label>{form.durationPreset==="custom"&&<label><span>DAYS</span><input type="number" min="1" max="3650" value={form.durationDays} onChange={e=>setForm({...form,durationDays:e.target.value})}/></label>}<label><span>MAX REDEMPTIONS</span><input type="number" min="1" max="100000" value={form.maxRedemptions} onChange={e=>setForm({...form,maxRedemptions:e.target.value})}/></label><label><span>EXPIRES (OPTIONAL)</span><input type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label><button className="primary" type="submit"><KeyRound/>Create code</button></form><Notice value={notice}/>{loading?<Loading/>:<Table columns={[
  {key:"code",label:"CODE",render:r=><div className="adminCode"><b>{r.code}</b><button title="Copy" onClick={()=>navigator.clipboard?.writeText(r.code)}><Copy/></button></div>},
  {key:"durationDays",label:"DURATION",render:r=>`${r.durationDays} days`},{key:"uses",label:"USES",render:r=>`${r.usedCount} / ${r.maxUses}`},{key:"status",label:"STATUS",render:r=><Badge tone={r.status}>{r.status}</Badge>},{key:"expiresAt",label:"EXPIRES",render:r=>when(r.expiresAt)},
  {key:"actions",label:"ACTIONS",render:r=><div className="adminRowActions"><button onClick={()=>showHistory(r)}>History</button><button onClick={()=>patch(r,r.status==="active"?"disabled":"active")}>{r.status==="active"?"Disable":"Enable"}</button><button className="danger icon" onClick={()=>remove(r)}><Trash2/></button></div>}
 ]} rows={codes} empty="No VIP codes have been created."/>}{history&&<div className="adminModalBackdrop" onClick={()=>setHistory(null)}><div className="adminModal" onClick={e=>e.stopPropagation()}><header><div><small>REDEMPTION HISTORY</small><h3>{history.code?.code}</h3></div><button onClick={()=>setHistory(null)}><XCircle/></button></header><Table columns={[{key:"discordUsername",label:"USER",render:r=><>{r.discordUsername||r.discordUserId}<small className="adminCellSub">{r.discordUserId}</small></>},{key:"guildName",label:"SERVER",render:r=><>{r.guildName||r.guildId}<small className="adminCellSub">{r.guildId}</small></>},{key:"redeemedAt",label:"REDEEMED",render:r=>when(r.redeemedAt)},{key:"result",label:"RESULT",render:r=><Badge>{r.result}</Badge>}]} rows={history.history||[]} empty="This code has not been redeemed."/></div></div>}</section>
}

export function TebexModule(){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState(null),[query,setQuery]=useState("");const load=async()=>{setLoading(true);try{setData(await api("/api/admin/tebex"))}catch(error){setNotice({text:error.message})}finally{setLoading(false)}};useEffect(()=>{load()},[]);if(loading)return <Loading/>;if(!data)return <Notice value={notice}/>;const payments=(data.payments||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));return <section className="adminModule"><div className="adminMetricGrid"><div><Server/><span><small>TEBEX</small><b>{data.config?.statusLabel||"Unknown"}</b><em>{data.config?.packageName}</em></span></div><div><ShieldCheck/><span><small>VIP PACKAGE</small><b>{data.config?.price||"—"}</b><em>ID {data.config?.packageId||"not configured"}</em></span></div><div><Wifi/><span><small>LAST WEBHOOK</small><b>{data.webhook?.label||"No activity"}</b><em>{when(data.webhook?.lastReceivedAt)}</em></span></div></div><Notice value={notice}/><div className="adminModuleToolbar"><div className="adminSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search payments"/></div><button onClick={load}><RefreshCw/>Refresh</button></div><h3 className="adminSectionTitle">Payments</h3><Table columns={[{key:"updatedAt",label:"DATE",render:r=>when(r.updatedAt||r.createdAt)},{key:"reference",label:"REFERENCE"},{key:"discordUserId",label:"DISCORD USER"},{key:"guildId",label:"SERVER ID"},{key:"amountLabel",label:"AMOUNT"},{key:"status",label:"STATUS",render:r=><Badge tone={r.status}>{r.status}</Badge>}]} rows={payments} empty="No Tebex payments are stored yet."/><h3 className="adminSectionTitle">Webhook events</h3><Table columns={[{key:"receivedAt",label:"RECEIVED",render:r=>when(r.receivedAt)},{key:"type",label:"TYPE"},{key:"paymentId",label:"PAYMENT"},{key:"handled",label:"HANDLED",render:r=><Badge tone={r.handled}>{r.handled}</Badge>}]} rows={data.webhookEvents||[]} empty="No webhook events are stored yet."/></section>
}

export function AssistantModule(){
 const[question,setQuestion]=useState(""),[answer,setAnswer]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(null);const ask=async text=>{const q=(text??question).trim();if(!q)return;setBusy(true);setNotice(null);try{setAnswer(await api("/api/admin/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q})}));setQuestion("")}catch(error){setNotice({text:error.message})}finally{setBusy(false)}};const quick=["Platform status","Recent errors","Recent payments","VIP activity","Support overview"];
 return <section className="adminModule adminAssistant"><div className="adminAssistantIntro"><Bot/><div><small>READ-ONLY PLATFORM ASSISTANT</small><h3>Ask about live BalticM data</h3><p>Answers are built from stored platform information and service checks.</p></div></div><div className="adminQuickActions">{quick.map(x=><button key={x} onClick={()=>ask(x)} disabled={busy}>{x}</button>)}</div><div className="adminAssistantAsk"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Ask: Which VIP subscriptions expire soon?"/><button onClick={()=>ask()} disabled={busy||!question.trim()}><Send/>{busy?"Checking…":"Ask"}</button></div><Notice value={notice}/>{answer&&<div className="adminAssistantAnswer"><small>{answer.intent?.replaceAll("_"," ")||"ANSWER"}</small><h3>{answer.reply}</h3>{answer.cards?.length>0&&<div className="adminMetricGrid compact">{answer.cards.map((card,index)=><div key={card.name||index}><CheckCircle2/><span><small>{card.name}</small><b>{card.status}</b><em>{card.detail}</em></span></div>)}</div>}{answer.rows?.length>0&&<Table columns={Object.keys(answer.rows[0]).slice(0,6).map(key=>({key,label:key.replace(/([A-Z])/g," $1").toUpperCase(),render:r=>key.toLowerCase().includes("at")?when(r[key]):String(r[key]??"—")}))} rows={answer.rows}/>}</div>}</section>
}

export function LogsModule(){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[category,setCategory]=useState("all"),[status,setStatus]=useState("all"),[notice,setNotice]=useState(null);const load=async()=>{setLoading(true);try{setData(await api(`/api/admin/logs?q=${encodeURIComponent(query)}&category=${encodeURIComponent(category)}&status=${encodeURIComponent(status)}`))}catch(error){setNotice({text:error.message})}finally{setLoading(false)}};useEffect(()=>{load()},[]);return <section className="adminModule"><div className="adminModuleToolbar wrap"><div className="adminSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search activity"/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{(data?.categories||[]).map(x=><option key={x}>{x}</option>)}</select><input className="adminStatusFilter" value={status} onChange={e=>setStatus(e.target.value)} placeholder="Status or all"/><button onClick={load}><RefreshCw/>Apply</button></div><Notice value={notice}/>{loading?<Loading/>:<Table columns={[{key:"createdAt",label:"DATE",render:r=>when(r.createdAt)},{key:"category",label:"CATEGORY",render:r=><Badge tone={r.category}>{r.category}</Badge>},{key:"action",label:"ACTION"},{key:"actorDiscordId",label:"ACTOR"},{key:"guildId",label:"SERVER"},{key:"reference",label:"REFERENCE"},{key:"status",label:"STATUS"},{key:"details",label:"DETAILS"}]} rows={data?.events||[]} empty="No stored events match these filters."/>}</section>
}

export function SettingsModule(){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState(null);const load=async()=>{setLoading(true);try{setData(await api("/api/admin/settings"))}catch(error){setNotice({text:error.message})}finally{setLoading(false)}};useEffect(()=>{load()},[]);if(loading)return <Loading/>;if(!data)return <Notice value={notice}/>;return <section className="adminModule"><div className="adminReadonly"><ShieldCheck/><div><small>GLOBAL OWNER SETTINGS</small><h3>Read-only production configuration</h3><p>{data.general?.note}</p></div><button onClick={load}><RefreshCw/>Refresh</button></div><div className="adminMetricGrid"><div><Server/><span><small>ENVIRONMENT</small><b>{data.system?.environment||"—"}</b><em>Production runtime</em></span></div><div><Database/><span><small>DATABASE</small><b>{data.system?.database?.status||"—"}</b><em>{data.system?.database?.message||"D1 query status"}</em></span></div><div><Wifi/><span><small>SERVICES</small><b>{data.system?.discord?.ok?"Online":"Attention needed"}</b><em>{data.system?.discord?.services?.length||0} checked</em></span></div><div><ExternalLink/><span><small>TEBEX</small><b>{data.system?.tebex?.configured?"Configured":"Configuration issue"}</b><em>Credentials shown as presence only</em></span></div></div><div className="adminSettingsGrid"><article><small>VIP LIMITS</small><h3>Current runtime values</h3><dl><div><dt>Default VIP duration</dt><dd>{data.premium?.defaultVipDurationDays} days</dd></div><div><dt>FREE reaction roles</dt><dd>{data.premium?.freeReactionRolesLimit}</dd></div><div><dt>VIP reaction roles</dt><dd>{data.premium?.vipReactionRolesLimit}</dd></div><div><dt>VIP Voice Create</dt><dd>{data.premium?.vipVoiceCreateLimit}</dd></div></dl></article><article><small>SERVICE HEALTH</small><h3>Live checks</h3><div className="adminServiceList">{(data.system?.discord?.services||[]).map(x=><div key={x.name}><span className={x.ok?"ok":"bad"}/><b>{x.name}</b><small>{x.kind}</small><em>{x.ok?"ONLINE":`HTTP ${x.status||0}`}</em></div>)}</div></article></div></section>
}
