import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{Activity,Bell,Bot,ChevronRight,CircleGauge,Gift,LayoutDashboard,Logs,Menu,Radio,Settings,Shield,Users,X,Zap}from"lucide-react";import"./style.css";
const logo="https://media.balticm.eu/media/site/1789671085906-96004b1e-3eb5-4f21-a47b-1e58bc088de2.png";
const nav=[["Dashboard",LayoutDashboard],["Bot Status",Activity],["Reaction Roles",Zap],["Announcements",Bell],["Giveaways",Gift],["Members & Roles",Users],["Logs",Logs],["Settings",Settings]];
function App(){const[open,setOpen]=useState(false),[health,setHealth]=useState(null);useEffect(()=>{fetch("/api/health").then(r=>r.json()).then(setHealth).catch(()=>setHealth({ok:false}));},[]);const online=health?.services?.some?.(x=>x.ok);return <div className="shell">
<aside className={open?"side open":"side"}><div className="brand"><img src={logo}/><div><b>BALTIC | MAYHEM</b><span>BOT CONTROL CENTER</span></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([n,I],i)=><button className={i===0?"active":""} key={n}><I/><span>{n}</span>{i===0&&<ChevronRight className="arrow"/>}</button>)}</nav><div className="sidefoot"><div className="pulse"/><div><b>Gateway</b><span>{health===null?"Checking…":online?"Connected":"Awaiting connection"}</span></div></div></aside>
<main><header><button className="hamb" onClick={()=>setOpen(true)}><Menu/></button><div><span className="eyebrow">DISCORD MANAGEMENT</span><h1>Dashboard</h1></div><div className="headright"><div className="live"><span/>LIVE</div><button className="login"><Shield/>Login with Discord</button></div></header>
<section className="hero"><div><span className="eyebrow">BALTICM.EU • COMMUNITY SYSTEM</span><h2>Your Discord.<br/><em>Under control.</em></h2><p>One place for Baltic Mayhem bot health, reaction roles, announcements, giveaways and server management.</p></div><div className="orb"><Bot/><span className="ring r1"/><span className="ring r2"/></div></section>
<section className="stats"><Card icon={Bot} label="MAIN BOT" value={health===null?"CHECKING":online?"ONLINE":"CONNECTING"} sub="BalticM.eu"/><Card icon={Radio} label="REACTION ROLES" value="ACTIVE" sub="Role automation"/><Card icon={Users} label="DISCORD" value="BALTIC MAYHEM" sub="Community server"/><Card icon={Zap} label="SYSTEM" value="READY" sub="Control center"/></section>
<div className="grid"><section className="panel wide"><div className="ptitle"><div><span className="eyebrow">SYSTEM OVERVIEW</span><h3>Bot services</h3></div><Activity/></div><Service name="BalticM.eu Main Bot" desc="Interactions & Discord services" state={health?.services?.[0]}/><Service name="Reaction Roles v3" desc="Gateway role automation" state={health?.services?.[1]}/><Service name="Cloudflare Control Center" desc="Dashboard frontend" state={{ok:true}}/></section>
<section className="panel"><div className="ptitle"><div><span className="eyebrow">QUICK ACCESS</span><h3>Management</h3></div><CircleGauge/></div>{[["Reaction Roles","Manage game & community roles",Zap],["Announcements","Publish server updates",Bell],["Giveaways","Create community giveaways",Gift],["Members & Roles","Server access control",Users]].map(([a,b,I])=><button className="quick" key={a}><I/><span><b>{a}</b><small>{b}</small></span><ChevronRight/></button>)}</section></div>
<footer><span>© 2026 Baltic Mayhem</span><span>PLAY TOGETHER • MANAGE SMARTER</span></footer></main></div>}
function Card({icon:I,label,value,sub}){return <div className="card"><div className="ico"><I/></div><div><span>{label}</span><b>{value}</b><small>{sub}</small></div></div>}
function Service({name,desc,state}){let s=state===undefined?null:!!state?.ok;return <div className="service"><div className={"dot "+(s===null?"wait":s?"ok":"bad")}/><div><b>{name}</b><span>{desc}</span></div><strong>{s===null?"CHECKING":s?"ONLINE":"OFFLINE"}</strong></div>}
createRoot(document.getElementById("root")).render(<App/>);